In [3]:
import pandas as pd

In [4]:
data=pd.read_csv("A1_data.csv")

In [5]:
data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

In [7]:
data.shape

(12330, 18)

In [8]:
data.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

In [9]:
data.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

In [13]:
#number of zeros
(data==0).sum()

Administrative              5768
Administrative_Duration     5903
Informational               9699
Informational_Duration      9925
ProductRelated                38
ProductRelated_Duration      755
BounceRates                 5518
ExitRates                     76
PageValues                  9600
SpecialDay                 11079
Month                          0
OperatingSystems               0
Browser                        0
Region                         0
TrafficType                    0
VisitorType                    0
Weekend                     9462
Revenue                    10422
dtype: int64

In [14]:
#missing value
data.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [15]:
data.mean(numeric_only=True)

Administrative                2.315166
Administrative_Duration      80.818611
Informational                 0.503569
Informational_Duration       34.472398
ProductRelated               31.731468
ProductRelated_Duration    1194.746220
BounceRates                   0.022191
ExitRates                     0.043073
PageValues                    5.889258
SpecialDay                    0.061427
OperatingSystems              2.124006
Browser                       2.357097
Region                        3.147364
TrafficType                   4.069586
Weekend                       0.232603
Revenue                       0.154745
dtype: float64

In [16]:
data.mode()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.0,0.0,0.2,0.0,0.0,May,2,2,1,2,Returning_Visitor,False,False

In [17]:
#train test
from sklearn.model_selection import train_test_split

In [22]:
x=data.drop("Revenue",axis=1)
y=data["Revenue"]

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [25]:
x_train

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
2026,0,0.000000,0,0.0,4,22.000000,0.050000,0.100000,0.000000,0.0,Mar,2,4,6,3,Returning_Visitor,True
5831,1,215.600000,2,8.0,27,2968.900000,0.021429,0.036905,0.000000,0.0,Nov,3,2,6,1,Returning_Visitor,False
5185,9,134.766667,0,0.0,17,347.547619,0.024242,0.042121,0.000000,0.0,May,3,2,4,4,Returning_Visitor,False
11530,7,105.375000,0,0.0,48,1268.116667,0.022902,0.027788,0.000000,0.0,Nov,1,1,8,1,Returning_Visitor,True
6413,11,251.309091,2,1655.4,80,1249.048358,0.003571,0.013744,8.517221,0.0,Sep,3,2,4,2,Returning_Visitor,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4735,0,0.000000,0,0.0,6,24.000000,0.133333,0.166667,0.000000,0.8,May,2,2,7,3,Returning_Visitor,False
264,0,0.000000,0,0.0,30,397.000000,0.000000,0.020000,0.000000,0.0,Mar,2,2,7,2,Returning_Visitor,False
5657,0,0.000000,0,0.0,5,0.000000,0.200000,0.200000,0.000000,0.0,Jul,3,2,2,13,Returning_Visitor,True
2009,0,0.000000,0,0.0,6,36.000000,0.066667,0.133333,0.000000,0.0,Mar,4,1,1,3,Returning_Visitor,True
1166,2,107.000000,0,0.0,3,56.000000,0.000000,0.040000,0.000000,0.0,Mar,1,1,3,2,New_Visitor,False

In [26]:
y_train

2026     False
5831     False
5185     False
11530    False
6413     False
         ...
4735     False
264      False
5657     False
2009     False
1166     False
Name: Revenue, Length: 9247, dtype: bool

In [27]:
x_test

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
1830,0,0.000000,0,0.000000,7,1018.000000,0.000000,0.028571,0.000000,0.0,Mar,2,2,1,2,Returning_Visitor,False
5894,0,0.000000,0,0.000000,4,145.200000,0.000000,0.025000,0.000000,0.0,Aug,2,4,7,2,Returning_Visitor,False
3952,8,41.000000,0,0.000000,34,1337.245455,0.013750,0.024214,0.000000,0.0,May,1,1,3,2,Returning_Visitor,False
3991,2,127.000000,0,0.000000,19,1431.666667,0.000000,0.010000,0.000000,0.2,May,2,2,4,2,Returning_Visitor,False
9630,5,46.142857,0,0.000000,51,1346.630231,0.007126,0.029720,0.000000,0.0,Nov,2,2,3,2,Returning_Visitor,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9699,0,0.000000,0,0.000000,9,427.000000,0.000000,0.025000,13.116828,0.0,Dec,1,1,1,2,New_Visitor,True
4292,0,0.000000,0,0.000000,4,19.600000,0.075000,0.108333,0.000000,0.0,May,3,2,6,4,Returning_Visitor,True
8476,0,0.000000,5,497.833333,26,851.666667,0.006452,0.018280,0.000000,0.0,Nov,2,2,1,2,New_Visitor,True
9230,0,0.000000,0,0.000000,2,35.500000,0.000000,0.100000,0.000000,0.0,Dec,2,6,1,11,Returning_Visitor,True
813,0,0.000000,0,0.000000,22,1310.500000,0.009524,0.028571,23.863593,0.0,Mar,2,2,1,1,Returning_Visitor,False

In [28]:
y_test

1830    False
5894    False
3952    False
3991    False
9630    False
        ...
9699     True
4292    False
8476    False
9230    False
813      True
Name: Revenue, Length: 3083, dtype: bool

In [29]:
sub1=data[data["Month"]=="Feb"]
sub1

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,0,0.0,0,0.0,6,163.250000,0.033333,0.033333,0.0,0.6,Feb,1,1,6,2,Returning_Visitor,False,False
180,0,0.0,0,0.0,17,284.250000,0.000000,0.011765,0.0,0.0,Feb,3,2,6,2,Returning_Visitor,True,False
181,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.6,Feb,4,2,1,3,Returning_Visitor,False,False
182,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,2,4,1,1,Returning_Visitor,False,False
183,0,0.0,0,0.0,8,260.000000,0.008333,0.025000,0.0,0.8,Feb,3,2,1,3,Returning_Visitor,True,False

In [30]:
sub2=data[(data["ExitRates"]>0.1) & (data["OperatingSystems"]==3)]
sub2

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
21,0,0.0,0,0.0,2,0.000000,0.200000,0.200000,0.0,0.0,Feb,3,3,1,3,Returning_Visitor,False,False
47,0,0.0,0,0.0,3,80.000000,0.066667,0.133333,0.0,0.2,Feb,3,2,1,3,Returning_Visitor,False,False
56,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.6,Feb,3,2,3,3,Returning_Visitor,False,False
69,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.2,Feb,3,2,3,3,Returning_Visitor,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11775,0,0.0,0,0.0,9,38.750000,0.120000,0.120833,0.0,0.0,Nov,3,2,1,13,Returning_Visitor,False,False
11993,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Dec,3,2,1,1,Returning_Visitor,False,False
12090,0,0.0,0,0.0,5,43.500000,0.140000,0.180000,0.0,0.0,Nov,3,3,1,3,Returning_Visitor,False,False
12174,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Dec,3,2,9,1,Returning_Visitor,True,False
12197,0,0.0,0,0.0,3,0.000000,0.200000,0.200000,0.0,0.0,Nov,3,2,1,10,Returning_Visitor,False,False

In [31]:
sub3=data[data["Revenue"]==True]
sub3

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
65,3,87.833333,0,0.00,27,798.333333,0.000000,0.012644,22.916036,0.8,Feb,2,2,3,1,Returning_Visitor,False,True
76,10,1005.666667,0,0.00,36,2111.341667,0.004348,0.014493,11.439412,0.0,Feb,2,6,1,2,Returning_Visitor,False,True
101,4,61.000000,0,0.00,19,607.000000,0.000000,0.026984,17.535959,1.0,Feb,1,1,7,4,Returning_Visitor,True,True
188,9,111.500000,1,48.50,49,1868.819697,0.000000,0.020709,1.706015,0.0,Mar,2,2,7,2,Returning_Visitor,False,True
196,2,56.000000,1,144.00,67,2563.783333,0.000000,0.005797,19.342650,0.0,Mar,2,2,4,2,New_Visitor,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12272,6,133.466667,0,0.00,44,2664.445833,0.002041,0.010884,97.860836,0.0,Nov,2,2,1,3,Returning_Visitor,True,True
12276,7,139.575000,0,0.00,30,986.500000,0.000000,0.011429,36.392861,0.0,Dec,2,10,1,2,New_Visitor,False,True
12311,1,0.000000,2,211.25,144,4627.489571,0.001361,0.020664,0.000000,0.0,Nov,2,2,1,2,Returning_Visitor,False,True
12312,7,150.357143,1,9.00,221,11431.001240,0.011149,0.021904,1.582473,0.0,Nov,2,5,1,2,Returning_Visitor,True,True
12313,3,16.000000,3,86.00,15,2773.500000,0.000000,0.030000,78.811725,0.0,Dec,2,2,1,2,Returning_Visitor,False,True

In [32]:
 import seaborn as sns

In [ ]:
sns.pairplot(data,hue="Revenue")